### ISSUE TITLE
Não consegui rodar na minha máquina

### ISSUE THREAD

**Issue by orlandosaraivajr** [gabriel-venezian/my-etl#3]
Tentei com Python 3.7

**Comment by pedrohsbarbosa99** [comment]
Tente executar o comando para instalar algumas dependencias:
sudo apt-get install libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
    libharfbuzz-dev libfribidi-dev libxcb1-dev
